# ABOUTME: Renders a markdown cheat-sheet from live Rule instances.
# ABOUTME: Groups rules by severity, one line per rule, suitable for @-reference from CLAUDE.md.
from __future__ import annotations

from gaudi.core import Rule, Severity

_HEADER = """\
# Gaudi Rules

> Generated by `gaudi cheat-sheet`. Do not edit by hand.
> Source: `src/gaudi/packs/` — change the rule's `recommendation_template` field, then regenerate.
"""

_SEVERITY_ORDER = (Severity.ERROR, Severity.WARN, Severity.INFO)

_SEVERITY_HEADINGS = {
    Severity.ERROR: "Errors",
    Severity.WARN: "Warnings",
    Severity.INFO: "Info",
}


def render_cheat_sheet(rules: list[Rule]) -> str:
    """Render a markdown cheat-sheet from a list of Rule instances.

    Rules are grouped by severity, sorted by code within each group.
    Each rule is one line: ``- **CODE ClassName** — recommendation``.
    """
    grouped: dict[Severity, list[Rule]] = {s: [] for s in _SEVERITY_ORDER}
    for rule in rules:
        grouped[rule.severity].append(rule)

    lines: list[str] = [_HEADER]

    for severity in _SEVERITY_ORDER:
        group = sorted(grouped[severity], key=lambda r: r.code)
        if not group:
            continue
        lines.append(f"## {_SEVERITY_HEADINGS[severity]}")
        lines.append("")
        for rule in group:
            recommendation = rule.recommendation_template
            class_name = type(rule).__name__
            lib_tag = f" [{rule.requires_library}]" if rule.requires_library else ""
            lines.append(f"- **{rule.code} {class_name}**{lib_tag} — {recommendation}")
        lines.append("")

    return "\n".join(lines)
