# ABOUTME: Unit tests for the cheat-sheet renderer service.
# ABOUTME: Uses synthetic rules to verify grouping, sorting, and output format.
from __future__ import annotations

from gaudi.core import Category, Rule, Severity
from gaudi.services.cheat_sheet import render_cheat_sheet


class _ErrorRule(Rule):
    code = "ERR-099"
    severity = Severity.ERROR
    category = Category.ERROR_HANDLING
    message_template = "test error"
    recommendation_template = "Fix the error immediately."


class _WarnRule(Rule):
    code = "WARN-050"
    severity = Severity.WARN
    category = Category.STABILITY
    message_template = "test warning"
    recommendation_template = "Consider improving stability."


class _InfoRule(Rule):
    code = "INFO-010"
    severity = Severity.INFO
    category = Category.CODE_SMELL
    message_template = "test info"
    recommendation_template = "Cosmetic improvement only."


class _LibraryRule(Rule):
    code = "LIB-001"
    severity = Severity.WARN
    category = Category.ARCHITECTURE
    message_template = "test lib"
    recommendation_template = "Use the library correctly."
    requires_library = "django"


class _SecondError(Rule):
    code = "ERR-001"
    severity = Severity.ERROR
    category = Category.ERROR_HANDLING
    message_template = "another error"
    recommendation_template = "Catch specific exceptions."


def test_render_groups_by_severity():
    rules = [_InfoRule(), _ErrorRule(), _WarnRule()]
    output = render_cheat_sheet(rules)
    # Errors section appears before Warnings, Warnings before Info
    err_pos = output.index("## Errors")
    warn_pos = output.index("## Warnings")
    info_pos = output.index("## Info")
    assert err_pos < warn_pos < info_pos


def test_render_sorts_by_code_within_group():
    rules = [_ErrorRule(), _SecondError()]
    output = render_cheat_sheet(rules)
    # ERR-001 should appear before ERR-099
    pos_001 = output.index("ERR-001")
    pos_099 = output.index("ERR-099")
    assert pos_001 < pos_099


def test_render_includes_recommendation():
    rules = [_WarnRule()]
    output = render_cheat_sheet(rules)
    assert "Consider improving stability." in output


def test_render_includes_class_name():
    rules = [_ErrorRule()]
    output = render_cheat_sheet(rules)
    assert "_ErrorRule" in output


def test_render_library_tag():
    rules = [_LibraryRule()]
    output = render_cheat_sheet(rules)
    assert "[django]" in output


def test_render_no_library_tag_when_none():
    rules = [_WarnRule()]
    output = render_cheat_sheet(rules)
    assert "[" not in output.split("## Warnings")[1].split("\n")[2]


def test_render_header():
    output = render_cheat_sheet([])
    assert "# Gaudi Rules" in output
    assert "Generated by `gaudi cheat-sheet`" in output
    assert "Do not edit by hand" in output


def test_render_empty_severity_omitted():
    rules = [_InfoRule()]
    output = render_cheat_sheet(rules)
    assert "## Errors" not in output
    assert "## Warnings" not in output
    assert "## Info" in output


def test_render_one_line_per_rule():
    rules = [_ErrorRule(), _WarnRule(), _InfoRule()]
    output = render_cheat_sheet(rules)
    rule_lines = [line for line in output.splitlines() if line.startswith("- **")]
    assert len(rule_lines) == 3
